### ISSUE TITLE
Github environment variables empty when used in 'values' section

### ISSUE THREAD

**Issue by pixelpiloten** [bitovi/github-actions-deploy-eks-helm#10]
Hi, been trying to use github environment variables like GITHUB_REF_NAME and GITHUB_RUN_ID in the  values section, but they turn up empty, my own created environment variables are populated though.

Here is my action job. The secret ${{ secrets.AWS_PIXEL_REGISTRY_URL }} works, as well as $APPLICATION_NAME, but not $GITHUB_REF_NAME or $GITHUB_RUN_ID.

```- name: Deploying helm chart
  uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
  env:
    REGISTRY_URL: ${{ secrets.<REDACTED> }}
    APPLICATION_NAME: application-test
  with:
    aws-access-key-id: ${{ secrets.<REDACTED> }}
    aws-secret-access-key: ${{ secrets.<REDACTED> }}
    aws-region: ${{ secrets.<REDACTED> }}
    cluster-name: pixel
    cluster-role-arn: ${{ secrets.<REDACTED> }}
    config-files: .helm/application-test/values.yaml
    chart-path: .helm/application-test
    namespace: default
    name: application-test
    values: 'image=${{ secrets.AWS_PIXEL_REGISTRY_URL }}:$APPLICATION_NAME-$GITHUB_REF_NAME-$GITHUB_RUN_ID'
```

**Comment by ccapell** [comment]
That's strange.  I can't think of anything in the code that would cause this, so it has to be something with the way GitHub parses the variables.  I'm thinking that the context values `${{ }}` get substituted before being sent to the docker container, and the environmental variables afterward in the container itself.  The reason APPLICATION_NAME works is that you have that set under `env:`  First, I would try this in your values line.

`values: 'image=${{ secrets.AWS_PIXEL_REGISTRY_URL }}:$APPLICATION_NAME-${{ github.ref_name }}-${{ github.run_id }}'`

My second suggestion would be to pass GITHUB_REF_NAME and GITHUB_RUN_ID in as environmental variables.

**Comment by pixelpiloten** [comment]
Hi, using ${{ github.ref_name }}-${{ github.run_id }} worked, thanks for the quick feedback :)
