### ISSUE TITLE
Support helm login so action can pull from private helm repos

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/github-actions-deploy-eks-helm#16]
If helm charts are behind auth, this action can't get to them without a separate prior step/action to pull the chart into the runner.

Helm provides `helm login`: https://helm.sh/docs/helm/helm_registry_login/

It would be nice for this action to surface the `helm login` params provided by the helm CLI.

more context: https://github.com/bitovi/github-actions-deploy-eks-helm/issues/14

**Comment by LeoDiazL** [comment]
OCI registries login is solved in PR #12
