### ISSUE TITLE
can --dry-run option be added to helm install

### ISSUE THREAD

**Issue by sushovan23** [bitovi/github-actions-deploy-eks-helm#30]
can `--dry-run` option be added to helm install. It will help in creating workflow checks.

**Comment by LeoDiazL** [comment]
Hi @sushovan23! 
Thanks for submitting an issue. Sounds pretty easy to implement. 

Keep in mind that this option will be added only to the install / uninstall commands. Is that what you are looking for?

**Comment by sushovan23** [comment]
Yes that’s correct. I plan to add it to commit checks so that helm chart/values file is verified before PR

**Comment by LeoDiazL** [comment]
Hey @sushovan23

We have an update in the PR #31 to this action in order to support the dry-run option.

You can test it out by changing your workflow yaml line to use a specific branch like this

```
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@30-can-dry-run-option-be-added-to-helm-install
```

Can you test it out and let us know if it's working as desired? 

Thanks!

**Comment by sushovan23** [comment]
looks good. test passed
