### ISSUE TITLE
Upgrade underlying go version

### ISSUE THREAD

**Issue by ChrisBellew** [bitovi/github-actions-deploy-eks-helm#35]
Thanks for providing this helpful tool! :pray::pray: 

This repo currently depends upon `alpine/k8s:1.26.1` for its base image which in turn depends upon helm version 3.2.1, which in turn uses go 1.13 which went out of support 3 years ago.

This is quite out of date and misses lots of security updates and features provided in newer versions of go/helm. Would you be interested in accepting PRs to bring these upstream deps up to date?

**Comment by ChrisBellew** [comment]
Hmm, I think I misspoke. Experimentally the base image does actually have helm 3.11.1.
```
docker run --rm alpine/k8s:1.26.1 helm version
```

I must have made a mistake in my tracing through the image versions so I'm closing this ticket.

**Comment by LeoDiazL** [comment]
@ChrisBellew thanks for opening the issue either way!
I'll bump the version when we cut a new release.
