### ISSUE TITLE
Feature request: Expose additional options to set values (e.g. `--set-string`)

### ISSUE THREAD

**Issue by joeycumines** [bitovi/github-actions-deploy-eks-helm#48]
The usage of `--set` can be problematic in certain scenarios, e.g. setting values like `1234`, as they'll be parsed as a `float64`.

There are additional options that can be used to mitigate this: https://helm.sh/docs/helm/helm_install/

Both `--set-string` and `--set-json` would be useful, with that latter being more useful for templating in actions, but the former probably more intuitive as default behavior.

A non-breaking way to resolve this would be to add additional `values_*` inputs, to the action.

**Comment by LeoDiazL** [comment]
Closing the issue due to inactivity. Feel free to reopen the issue if needed.
