### ISSUE TITLE
Make it possible to use helm upgrade --atomic

### ISSUE THREAD

**Issue by sirantd** [bitovi/github-actions-deploy-eks-helm#6]
Hi,

Using helm for deployment usually means reverting back if failed. It can be achieved by adding --atomic flag.
Is it something you are willing to add?

**Comment by mickmcgrath13** [comment]
@sirantd here's a PR: https://github.com/bitovi/github-actions-deploy-eks-helm/pull/7 (thanks @ccapell!)

**Comment by ccapell** [comment]
Option added for the atomic flag
